### PR TITLE
Possible fix for #11

### LINKED ISSUE #11: Fetching comment parent clears children comments
**Describe the bug**

If I refresh a comment, then it loads in the comment replies. However, if I fetch the parent, then it clears the replies.

**To Reproduce**
1. Make comment from URL
2. Refresh comment and check for replies
3. Fetch parent
4. Check for replies

**Expected behavior**

The children should not be cleared.

**Code/Logs**

```python
url = "https://www.reddit.com/r/anime/comments/il7y3i/rezero_kara_hajimeru_isekai_seikatsu_season_2/g3q1k1m/?utm_source=share&utm_medium=ios_app&utm_name=iossmf"
comment = await reddit.comment(url=url)
print(len(comment.replies))
await comment.refresh()
print(len(comment.replies))
await comment.parent()
print(len(comment.replies))
```

Output: 
```
0
6
0
```

**System Info**
 - OS: Mac OS 10.15.6
 - Python: 3.8.5
 - Async PRAW Version: 7.1.0

### PR DESCRIPTION
**Pull request by LilSpazJoekp**
Fixes #11

## Feature Summary and Justification

This adds a check to see if the comment and comment's submission is already fetched. When fetching a comment, its replies get cleared. 

## References

* 
*

### CODE REVIEW

**Review by PythonCoderAS — APPROVED** [review]
Seems simple enough. Maybe this should be integration-tested.

**Comment by LilSpazJoekp** [comment]
What do you have in mind for that?

**Comment by PythonCoderAS** [comment]
My big had code to reproduce the issue. I think if we simply use that, it won't be too hard.

```python
url = "https://www.reddit.com/r/anime/comments/il7y3i/rezero_kara_hajimeru_isekai_seikatsu_season_2/g3q1k1m/?utm_source=share&utm_medium=ios_app&utm_name=iossmf"
comment = await reddit.comment(url=url)
assert len(comment.replies) == 0
await comment.refresh()
assert len(comment.replies) > 0
await comment.parent()
assert len(comment.replies) > 0
```

**Comment by LilSpazJoekp** [comment]
Do you want to make a test for it since its your code?

**Comment by PythonCoderAS** [comment]
@LilSpazJoekp I forgot how to setup all the code for an integration test, and as I have never contributed towards asyncpraw, have no clue how to do so for the async variant.

**Comment by LilSpazJoekp** [comment]
The setup is exactly the same as praw except you have to install a custom version of vcrpy:

```sh
pip install https://github.com/LilSpazJoekp/vcrpy/archive/asyncpraw.zip --upgrade
```

See this for an example:
https://github.com/praw-dev/asyncpraw/blob/fb311fc33afa399834666ca18c95ec9337ba4970/tests/integration/models/reddit/test_comment.py#L103-L110

**Pull request merged**
