### PR TITLE
await missing in example 

### PR DESCRIPTION
**Pull request by kaif-00z**
Fixes # (provide issue number if applicable)

## Feature Summary and Justification

This pull request provides ...

## References

-

### CODE REVIEW

**Review by LilSpazJoekp — APPROVED** [review]
Nice catch!

**Comment by kaif-00z** [comment]
> Nice catch!

hi , you use telegram? , i have some questions and some bugs to discuss about.

**Comment by LilSpazJoekp** [comment]
I do not unfortunately but you're welcome to join our [Slack](https://join.slack.com/t/praw/shared_invite/enQtOTUwMDcxOTQ0NzY5LWVkMGQ3ZDk5YmQ5MDEwYTZmMmJkMTJkNjBkNTY3OTU0Y2E2NGRlY2ZhZTAzMWZmMWRiMTMwYjdjODkxOGYyZjY)

**Comment by kaif-00z** [comment]
> I do not unfortunately but you're welcome to join our [Slack](https://join.slack.com/t/praw/shared_invite/enQtOTUwMDcxOTQ0NzY5LWVkMGQ3ZDk5YmQ5MDEwYTZmMmJkMTJkNjBkNTY3OTU0Y2E2NGRlY2ZhZTAzMWZmMWRiMTMwYjdjODkxOGYyZjY)

no reply and response 😞

**Pull request merged**
