### PR TITLE
fix: enables stream to pull new items when the before_attribute has been deleted

### PR DESCRIPTION
**Pull request by cmays90**
Fixes https://github.com/praw-dev/asyncpraw/issues/16

## Feature Summary and Justification

This feature fixes an issue where the stream would stall when the last item pulled was deleted.  This fix matches the functionality and implementation of main PRAW.

### CODE REVIEW

**Comment by LilSpazJoekp** [comment]
I can't remember why this was different than the main PRAW. If I remember correctly, I had issues with tests passing without the change. I will do some digging.

**Review by LilSpazJoekp — CHANGES_REQUESTED** [review]
Could you add a change log entry?

**Comment by cmays90** [comment]
Updated.

**Comment by LilSpazJoekp** [comment]
Could you take a look at the check errors?

**Comment by vikasbhatia** [comment]
Hi @LilSpazJoekp and @cmays90, any ETA on when this fix will be merged into asyncpraw? I recently switched from PRAW and I'm facing the exact same issue described in https://github.com/praw-dev/asyncpraw/issues/16 where a subreddit stream just stops working after a little while, no exceptions/errors logged.

I was thinking of installing this PR directly but I see some failing checks - would that be a problem? 

Thank you for all your work.

**Comment by LilSpazJoekp** [comment]
> I was thinking of installing this PR directly but I see some failing checks - would that be a problem?

Most likely not. However, since tests are not currently passing, I cannot guarantee its stability. Though, looking at the failing tests, it appears it just needs the tests rerecorded. That being said, you are more than welcome to use this version however, I won't accept any new issues regarding said version.

**Comment by LilSpazJoekp** [comment]
@cmays90 Could you add yourself to AUTHORS.rst please? After that, I'll finish this up for you. Thanks!

**Review by LilSpazJoekp — APPROVED** [review]

**Comment by LilSpazJoekp** [comment]
I got this finished up and merged for you. Thanks for the PR!

**Pull request merged**
