### PR TITLE
Connect websocket earlier

### PR DESCRIPTION
**Pull request by LilSpazJoekp**
(cherry picked from commit 02325b0002932ba2abb477f51d9383679f749775)

## References

- https://github.com/praw-dev/praw/pull/1591

### CODE REVIEW

**Comment by LilSpazJoekp** [comment]
@jarhill0 Could you take a look at this? I am not sure how you recorded some of the the tests (especially for the various timeouts).

**Comment by jarhill0** [comment]
Can you elaborate on which tests you're referring to?

These timeout tests are just stubbed with the `mock` library, I think: https://github.com/praw-dev/asyncpraw/pull/43/commits/28d45ad0a7a7fe61686aae443011c4984177f148#diff-a0329ec7635282c775788423c0a7b7c87d5d9c1fc29cb8f95bdc10650b1fff18R623

**Comment by LilSpazJoekp** [comment]
Okay upon looking into this further, I don't time some of the timeout test cases apply to the WebSocket client in `aiohttp`.

**Comment by LilSpazJoekp** [comment]
@jarhill0 Could you take a look at this?

**Review by jarhill0 — COMMENTED** [review]
Sorry for the late review — looks good!

**Pull request merged**
